export const TASK_TEMPLATES = [
  {
    position: 'Receiver',
    color: 'blue',
    icon: 'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4',
    daily: [
      'លើពFloor, Piramite និងRefill មួយជ (12:00pm–13:00pm)',
      'Prepare items IBT, RTW and Store Claim',
      'Receive (Chill, Dry, Supplies)',
      'Prepare Level 7 and clean',
      'Break',
      'Receive (Chill & Frozen, Dry, Supplies)',
      'Check Auto post, IBT (in & out), GR',
      'Prepare documents (ITB, GR, Return,...)',
      'Prepare roll cage in Back Store',
      'កកអម្ (19:30–20:00)',
      'ការទំនិញមួយជ មុនចេញទៅផ្ទះ + ប្រឡូកាកថ្ងៃ (20:00–21:00)',
      'Update pending job in group',
    ],
    tasks: [
      'Report expire Level 7, floor and piramite',
      'Complete expire report',
    ],
  },
  {
    position: 'Stock Officer',
    color: 'green',
    icon: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4',
    daily: [
      'Meeting with Store head',
      'ដើរFloor, Piramite និងRefill មួយជ',
      'Prepare items IBT, RTW and Store Claim',
      'Receive',
      'Prepare Level 7 and clean',
      'Break',
      'Receive (Chill & Frozen, Dry, Supplies)',
      'Check Auto post, IBT (in & out), GR',
      'Prepare documents (ITB, GR, Return,..)',
      'Prepare roll cage in Back Store',
      'កកអ្នក (19:30–20:00)',
      'ការទំនិញមួយជ មុនចេញទៅផ្ទះ + ប្រឡូកាកថ្ងៃ (20:00–21:00)',
      'Update pending job in group',
      'Prepare Products on shelves and refill stock',
      'Display (13:00pm to 14:00pm)',
      'Expiry Clean (14:00pm–15:00pm)',
      'Expiry report',
      'Check price missing by rows',
      'Prepare Product on sale floor before leave',
    ],
    tasks: [
      'Complete expire report',
    ],
  },
  {
    position: 'Senior Stock',
    color: 'yellow',
    icon: 'M13 7h8m0 0v8m0-8l-8 8-4-4-6 6',
    daily: [
      'Morning talk with Store head',
      'Look around Fresh',
      'ទំណាក់ទំនងនិងរៀបបន្ទប់ស្ងោរ (7:30–8:30)',
      'Scan and បិតស្លឹក Markdown (8:30–8:50) Meat',
      'Check and order fresh on mobile device',
      'Check Egg, Tofu, Kimchi',
      'Record temperature',
      'Check missing price ticket',
      'CH08 9:35 ដល់រសៀង 10:35',
      'Break',
      'Check Exp, FEFO, Clean, Return, Markdown',
      'Check Markdown, and clean',
      'ស្ពួ Sushi 50% (19:30–19:45)',
      'Prepare stock on sale floor before leave',
      'Expiry Record (7:30PM–8:00PM)',
      'ការFresh និងFZ ដើរស្នាកថ្ងៃមុនចេញទៅផ្ទះ',
    ],
    tasks: [
      'Check items promotion next month',
    ],
  },
  {
    position: 'Department Supervisor',
    color: 'orange',
    icon: 'M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4',
    daily: [
      'Morning talk with store head',
      'Open Store',
      'Look around Store',
      'Check price change',
      'Check email, WhatsApp and Telegram',
      'Prepare Product for SOD',
      'Spot check items promotion',
      'Refill stock on sale floor',
      'Check missing price label, A6, 2up and A4',
      'Break',
      'Look around Store',
      'Check email, WhatsApp and Telegram',
      'Check Exp, FEFO, Clean, Return, Markdown',
      'Check stock',
      'Do markdown',
      'Check email, WhatsApp and Telegram',
      'Check adjust stock',
      'Check System RTA, RTV, RTW, IBT in out',
      'Write off Dry and fresh',
      'Prepare stock on sale floor before leave',
      'Expiry Record warehouse',
      'Check items promotion',
      'Arrange meeting with team member',
      'Check LE 50% 70%',
    ],
    tasks: [
      'Check replenishment (Dry top 1000 items) and review',
      'Check all promotion Monthly / Weekly',
      'Lead team meeting',
      'Check items promotion next month',
      'Training with Store head on SOP',
      'Provide customer services, building customer loyalty, checking customer needs',
    ],
  },
  {
    position: 'Assistant Supervisor',
    color: 'purple',
    icon: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z',
    daily: [
      'Morning talk with store head',
      'Go to office, enter cash float',
      'Prepare cash set for cashier and prepare document for treasury with sale money by day sent to bank',
      'Prepare document, keep at office and take the money for bank',
      'Check and prepare document all put on the table for manager sign',
      'Check and control cashier about service to customer',
      'Prepare cash set for cashier and Shift close cashier, take cash sale total at office',
      'Break',
      'Prepare cash float & petty cash, prepare cash float to small cash change with supply',
      'Go to facilitate cashier is work with Service to customer',
      'Provide Customer Service and review on clean around counter cashier',
      'Provide Customer Service – Item promotion monthly, Wow promotion weekly',
      'Provide Customer Service about the membership App and promotion',
      'Spot check schedule clean',
    ],
    tasks: [
      'Surprise cash count with store head',
      'Review schedule cashier to counter',
      'Request petty cash claim',
      'Surprise Cash Count (actual count) on the cash float and petty cash',
      'Training with Store head on SOP',
      'Make new books report for new month',
    ],
  },
  {
    position: 'Manager',
    color: 'red',
    icon: 'M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z',
    daily: [
      'Morning talk with Store head',
      'Open POS, Scal, Acl, ABA, Wing, Nham24 machine POS, check the record machine',
      'Hand Over cash float to cashier',
      'Count Money and check the document cash management',
      'Prepare checkout counter',
      'Remove expired, expire check, shelves cleaning, fresh quality check and cashiering, FEFO',
      'Check Expire bakery',
      'Prepare document sent to office',
      'Prepare Cash sale for Bank',
      'Witness the sales pickup by the banking agent (World Bridge)',
      'Write and sign on the cashier documents: void report, cancel transaction report, return report, expense report (petty cash)',
      'Standby Cashier',
      'Close sale report POS (End Day) and other task assign by Cashier',
      'Check on customers complaint and team members job assigned',
      'Cleaning by monthly schedule (FS)',
      'Check for promotion items, cashier promoting and stock availability at check out counter',
      'End shift EOD and cash consolidation back end office',
      'Prepare print Cashier document (Appendices 14)',
      'Stand by at cashier check out and support to stock team to prepare the dry product',
    ],
    tasks: [
      'Surprise cash count Staff',
      'Update cash collection authorized list from treasury team',
      'Cash collection list report to SM-office',
      'Training FS & IA to team member',
    ],
  },
  {
    position: 'Receiving',
    color: 'teal',
    icon: 'M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4',
    daily: [
      'Morning talk with Store head',
      'Cleaning office',
      'Preparation documents send office',
      'Check price adjustment',
      'Make price markdown fresh items and dry',
      'Prepare file Return & Markdown to team',
      'Check email & take action',
      'Preparation documents IBT, RTW, RTV, PO',
      'Preparation documents FS',
      'Make documents markdown & write-off Fresh & Dry',
      'Spot check document IBT, RTW, RTV, PO, FS, HS',
    ],
    tasks: [
      'Spot check Cadena staff',
      'Send file & Make price Weekly promotion to team',
      'Process Adjust in system',
      'Camera & Scalst report',
      'Report expire in back store',
      'Order stationery and POS',
    ],
  },
  {
    position: 'Stock Officer (Other)',
    color: 'gray',
    icon: 'M4 6h16M4 10h16M4 14h16M4 18h16',
    daily: [
      'Morning talk with Store head',
      'Check and update task status',
      'Prepare daily report',
      'Review team task progress',
      'Update pending job in group',
    ],
    tasks: [
      'Complete weekly summary report',
    ],
  },
]

export const STAFF_TEMPLATES = [
  {
    name: 'Srou Chenda',
    role: 'Senior Store Manager',
    color: 'red',
    daily: [
      'Open Store',
      'Review the whole store situation to be ready for opening (equipment, cleanliness, stock availability)',
      'Check Email, WhatsApp & Telegram for task update',
      'Check task to do — clear pending tasks and focus on new tasks',
      'Check Open POS System',
      'Morning talk with team',
      'Check the high value and sensitive items',
      'Spot check on the 50% off area',
      'Spot check missing price ticket',
      'Spot check gap check',
      'Check promotion display, POSM and stocks availability',
      'Update and check Sale report, shrinkage report and Markdown report',
      'Bank-in the sales money with chief cashier / team leader or witness sales cash pickup by banking agent',
      'Check and sign cashier documents (void report, cancel transaction, return report, expense report, all appendices)',
      'Review CCTV record, cancel, update individual group',
      'Review all audit documents (internal & food safety)',
      'Update checklist individual group',
      'Check Order Fresh',
      'Provide customer services, building customer loyalty, checking customer needs',
      'Master and spot check expired product on shelf',
      'Spot check stock',
      'Check email, Telegram and WhatsApp',
      'Lunch Break',
      'Look around store / back store',
      'Check email, Telegram and WhatsApp',
      'Check cleaning in whole store',
      'Perform weekly and monthly task',
      'Review stock to refill for top sell',
      'Handover pending tasks to Dept. supervisor',
      'Spot check on guard and janitor\'s attendance',
      'Unlock safe box password',
      'Lock safe box password',
      'Update important information to AMs and OD in a timely manner',
      'Arrange and inform team member to complete the ad-hoc task',
      'Check and follow up on PPD and marketing pending purchase request',
      'Review and take action on shrinkage, markdown, and sales',
      'Follow up with Receiver on pending documents (IC pending, IU pending, PO pending, Changing report, PRR)',
      'Check Email, WhatsApp & Telegram for task update',
      'Review job assignment from team in store to make sure they perform their tasks',
      'Review the whole task for summary — list pending/complete for tomorrow follow-up',
      'Send daily report to AM for information',
    ],
    weekly: [
      'Surprise Cash Count on the Cash float and Petty Cash',
      'Bi-Weekly Internal Meeting',
      'Verify Documentation (Food Safety and Internal Audit)',
      'Spot check Expired record',
      'Update Sale Report App',
      'Check FFC Report',
      'CCTV spot check',
      'Check Sheet Code Cadena System',
      'Check Axonify All Staff',
      'Review stock cover day',
      'Check Document IBT, GIT, OP, RTW with System RTA',
      'Check and Follow Up on PPD and Marketing',
      'Check Document IA, NSF, H&S',
      'Review MinMax Order',
      'Spot Check Staff Cleaner',
      'Spot Check JA All Team Member',
      'Follow up on permanent delete items, low stock items (SOH 1,2,3), slow moving items, negative BOH, weekly stock adjustment, and 3-month no-sales items',
    ],
    monthly: [
      'One-on-one meeting with store supervisor and department supervisor',
      'Training store supervisor on the SOP',
      'Arrange and review staff schedule, promotions, HR forms, and update headcount to HR department',
      'Welcome new joiners, introduce to team, and arrange buddy system',
      'Stocktake (Fresh/Dry) planning and arrangement',
      'Execute space rental and planogram',
      'Review all audit documents (internal & food safety) — ensure 100% correct and compliant',
      'Price survey and competitor visit',
      'One-on-one meeting with team members to review performance',
      'Sales forecast for next month',
      'Fixed asset counting',
    ],
    quarterly: [
      'Change safe box password',
      'Staff performance appraisal',
    ],
  },
  {
    name: 'Samon An',
    role: 'Assistant Department',
    color: 'orange',
    daily: [
      'Meeting, Check staff attendance and uniform',
      'Look around Store',
      'Spot Check 50%',
      '12:00PM–12:15PM — Check photos and send to Group',
      'Signature on cash management',
      'Check email, Telegram and WhatsApp',
      '12:15PM–2:00PM — Manage team member performance',
      'Break',
      'Look Around Store',
      'Check email, Telegram and WhatsApp',
      'Spot Check Exp, FEFO, Clean, Return, Markdown',
      'Handover pending task from Store Head',
      'Provide customer services, building customer loyalty, checking customer needs',
      'Cycle count',
      'Spot Check Price Missing, Price Promotion',
      'Spot check spoil fresh',
      'Check staff prepare products',
      'Make sure store is ready for tomorrow morning operation',
      'Check the end of the store',
      'Spot check on security when staff leave the stores',
      'Check around store before leaving',
      'Check the sales report and update daily sales in WhatsApp group and email',
      'Unlock safe box password',
      'Lock safe box password',
      'Unlock and lock safe box password',
    ],
    weekly: [
      'Performing store manager role when store manager is not in the store',
      'Request create/delete users in RTA system',
      'Check and sign cashier documents (void report, cancel transaction, return report, expense report, all appendices)',
      'Morning talk, Check staff attendance and uniform',
      'Weekly internal meeting with team',
      'Check master order (Fresh) + MinMax',
      'Check permanent delete items, low stocks (SOH 1,2,3), slow moving items, negative BOH, weekly stock adjustment, 3-month no-sales items',
      'Surprise Cash Count (actual count) on cash float and petty cash',
      'Check replenishment (Dry for top 1000 items) and review',
      'Calibration 4 times a month',
      'Order Egg',
      'Order Link fresh every Thursday',
      'Reason Business Insight',
      'Check items promotion next month',
    ],
    monthly: [
      'Change safe box password',
      'Training with Store Manager on SOP',
      'One-on-one meeting with Store Head',
      'One-on-one meeting with team members',
      'Manager Log Book 1 Month',
      'Review all audit documents (internal & food safety) — ensure 100% correct and compliant',
    ],
    quarterly: [],
  },
  {
    name: 'Soy Solpiseth',
    role: 'Assistant Supervisor',
    color: 'purple',
    daily: [
      'Morning talk with store head',
      'Open Store',
      'Look around Store',
      'Check price change',
      'Check email, WhatsApp and Telegram',
      'Prepare Product for SOD',
      'Spot check items promotion',
      'Refill stock on sale floor',
      'Check missing price label, A6, 2up and A4',
      'Break',
      'Look around Store',
      'Check email, WhatsApp and Telegram',
      'Check Exp, FEFO, Clean, Return, Markdown',
      'Check stock',
      'Do markdown',
      'Check email, WhatsApp and Telegram',
      'Check adjust stock',
      'Check System RTA, RTV, RTW, IBT in/out',
      'Write off Dry and Fresh',
      'Prepare stock on sale floor before leaving',
      'Expiry Record warehouse',
      'Check items promotion',
      'Arrange meeting with team member',
      'Check 50% / 70% shelves',
    ],
    weekly: [
      'Check replenishment (Dry for top 1000 items) and review',
      'Scale testing',
      'Check all promotions (Monthly, Weekly...)',
      'Lead team to organize warehouse',
      'Check items promotion next month',
    ],
    monthly: [
      'Training with Store Head on SOP',
      'Provide customer services, building customer loyalty, checking customer needs',
    ],
    quarterly: [],
  },
  {
    name: 'Yoeun Ravit',
    role: 'Department Supervisor',
    color: 'green',
    daily: [
      'Morning talk with store head',
      'Open Store',
      'Look around Store',
      'Arrange Fresh products (8:00–8:30)',
      'Lead staff to clear stock from Roll cage, Level 7, warehouse (8:30AM–10:00AM)',
      'Check milk and all Chiller items (10:00–11:00)',
      'Take photos (11:00–11:30)',
      'Report Expired Cheese',
      'Break',
      'Record temperature in fridge (14:00–14:10)',
      'Check email, WhatsApp and Telegram',
      'Check Exp, FEFO, Clean, Return, Markdown',
      'Check stock',
      'Check and adjust stock — Fresh, Milk',
      'Order fresh on checklist',
      'System Control (Store Claim, IBT, RTV, RTW, Auto receive)',
      'Write off Fresh (15:30–16:00)',
      'Receiving and temperature record',
      'Support checkout and customer service',
      'Expiry Record',
      'Check items promotion',
      'FZ cleaning',
      'Arrange meeting with team member',
    ],
    weekly: [
      'Review top shrinkage & Markdown',
      'Scan and count fresh milk',
    ],
    monthly: [
      'Training with Store Head on SOP',
      'Provide customer services, building customer loyalty, checking customer needs',
    ],
    quarterly: [],
  },
  {
    name: 'Vuthy Devith',
    role: 'Receiver',
    color: 'blue',
    daily: [
      'Check floor, pyramid and refill (12:00PM–1:00PM)',
      'Prepare items IBT, RTW and Store Claim',
      'Receive (Chill, Dry, Supplies)',
      'Prepare Level 7 and clean',
      'Break',
      'Receive (Chill & Frozen, Dry, Supplies)',
      'Check Auto post, IBT (in & out), GR',
      'Prepare documents (IBT, GR, Return...)',
      'Prepare roll cage in Back Store',
      'Record fridge temperature (19:30–20:00)',
      'Scan items before leaving + make price labels (20:00–21:00)',
      'Update pending job in group',
    ],
    weekly: [
      'Report expire — Level 7, floor and pyramid',
    ],
    monthly: [
      'Complete expire report',
    ],
    quarterly: [],
  },
  {
    name: 'Touch Vicheat',
    role: 'Stock Officer',
    color: 'teal',
    daily: [
      'Meeting with Store Head',
      'Check floor, pyramid and refill',
      'Prepare items IBT, RTW and Store Claim',
      'Receive',
      'Prepare Level 7 and clean',
      'Break',
      'Receive (Chill & Frozen, Dry, Supplies)',
      'Check Auto post, IBT (in & out), GR',
      'Prepare documents (IBT, GR, Return...)',
      'Prepare roll cage in Back Store',
      'Record fridge temperature (19:30–20:00)',
      'Scan items before leaving + make price labels (20:00–21:00)',
      'Update pending job in group',
      'Scan items before leaving + make price labels',
    ],
    weekly: [],
    monthly: [
      'Complete expire report',
    ],
    quarterly: [],
  },
  {
    name: 'Tep Sovanaroth',
    role: 'Stock Officer',
    color: 'yellow',
    daily: [
      'Morning talk with Store Head',
      'Look around Fresh',
      'Unload and arrange products on shelves (7:30–8:30)',
      'Scan and apply Markdown stickers (8:30–8:50) — Meat',
      'Check and order fresh on mobile device',
      'Check Egg, Tofu, Kimchi',
      'Record temperature',
      'Check missing price ticket',
      'Arrange chiller and fruit display CH08 (9:35–10:35)',
      'Break',
      'Check Exp, FEFO, Clean, Return, Markdown',
      'Check Markdown and clean',
      'Scan Sushi 50% (19:30–19:45)',
      'Prepare stock on sale floor before leaving',
      'Expiry Record (7:30PM–8:00PM)',
      'Scan Fresh & FZ — check price labels before leaving',
    ],
    weekly: [
      'Check items promotion next month',
    ],
    monthly: [],
    quarterly: [],
  },
  {
    name: 'Pak Panhchakpor',
    role: 'Stock Officer',
    color: 'green',
    daily: [
      'Meeting with Store Head',
      'Prepare products on shelves and refill stock',
      'Display and arrange products (1:30PM–2:30PM)',
      'Check Expiry, clean dirty areas (4:00PM–5:00PM)',
      'Break',
      'Check product at back store and refill stock on sale floor',
      'Check price missing by rows',
      'Prepare product on sale floor before leaving',
      'Find trolley',
      'Scan items before leaving + make price labels (8:00PM–9:00PM)',
      'Prepare product on sale floor before leaving',
      'Clear back store',
    ],
    weekly: [],
    monthly: [
      'Complete expire report',
    ],
    quarterly: [],
  },
  {
    name: 'Heng Sovanaroth',
    role: 'Stock Officer',
    color: 'blue',
    daily: [
      'Meeting with Store Head',
      'Prepare products on shelves and refill stock',
      'Display and arrange products (1:00PM–2:00PM)',
      'Check Expiry, clean dirty areas (2:00PM–3:00PM)',
      'Break',
      'Arrange products on shelves',
      'Expiry report',
      'Check price missing by rows',
      'Prepare product on sale floor before leaving',
      'Scan items before leaving + make price labels (7:30PM–8:00PM)',
      'Complete tasks assigned by supervisor',
    ],
    weekly: [],
    monthly: [
      'Complete expire report',
    ],
    quarterly: [],
  },
  {
    name: 'Pav Lin',
    role: 'Stock Officer',
    color: 'teal',
    daily: [
      'Meeting with Store Head',
      'Prepare products on shelves and refill stock',
      'Display and arrange products (1:00PM–2:00PM)',
      'Check Expiry, clean dirty areas (2:00PM–3:00PM)',
      'Break',
      'Arrange products on shelves',
      'Expiry report',
      'Check price missing by rows',
      'Prepare product on sale floor before leaving',
      'Scan items before leaving + make price labels (7:30PM–8:00PM)',
      'Complete tasks assigned by supervisor',
    ],
    weekly: [],
    monthly: [
      'Complete expire report',
    ],
    quarterly: [],
  },
  {
    name: 'Mach Maomany',
    role: 'Assistant Supervisor Cashier',
    color: 'purple',
    daily: [
      'Morning talk with store head',
      'Go to office — enter cash float',
      'Prepare cash set for cashier and prepare document for treasury with sale money to be sent to bank',
      'Prepare document at office and take money for bank',
      'Check and prepare documents for manager signature',
      'Check and control cashier service to customer',
      'Prepare cash set for cashier and shift close cashier — take cash sale total at office',
      'Break',
      'Prepare cash float & petty cash — prepare small cash change with supply',
      'Facilitate cashier work and service to customer',
      'Provide Customer Service and review cleanliness around cashier counter',
      'Provide Customer Service — item promotion, Monthly/Wow/Weekly promotions',
      'Provide Customer Service about Membership App and promotions',
      'Spot check cleaning schedule',
    ],
    weekly: [
      'Surprise cash count with store head',
      'Review cashier schedule at counter',
      'Request petty cash claim',
    ],
    monthly: [
      'Surprise Cash Count (actual count) on cash float and petty cash',
      'Training with Store Head on SOP',
      'Make new report books for new month',
    ],
    quarterly: [],
  },
  {
    name: 'Hel Mealea',
    role: 'Senior Cashier',
    color: 'pink',
    daily: [
      'Morning talk with store head',
      'Go to office — enter cash float',
      'Prepare cash set for cashier and prepare document for treasury with sale money to be sent to bank',
      'Prepare document at office and take money for bank',
      'Check and prepare documents for manager signature',
      'Check and control cashier service to customer',
      'Prepare cash set for cashier and shift close cashier — take cash sale total at office',
      'Break',
      'Prepare cash float & petty cash — prepare small cash change with supply',
      'Facilitate cashier work and service to customer',
      'Provide Customer Service and review cleanliness around cashier counter',
      'Provide Customer Service — item promotion, Monthly/Wow/Weekly promotions',
      'Provide Customer Service about Membership App and promotions',
    ],
    weekly: [
      'Surprise cash count with store head',
      'Spot check cleaning schedule',
      'Review cashier schedule at counter',
      'Request petty cash claim',
    ],
    monthly: [
      'Surprise Cash Count (actual count) on cash float and petty cash',
    ],
    quarterly: [],
  },
  {
    name: 'Vutha Sothea',
    role: 'Chief Cashier',
    color: 'orange',
    daily: [
      'Morning talk with Store Head',
      'Open POS, Scale, ACL, ABA, Wing, Nham24 machine — check record machine',
      'Hand over cash float to cashier',
      'Count money and check cash management document',
      'Prepare checkout counter',
      'Remove expired items, expire check, shelves cleaning, fresh quality check, cashiering, FEFO',
      'Check Expire bakery',
      'Prepare document sent to office',
      'Prepare Cash sale for Bank',
      'Witness the sales pickup by the banking agent (World Bridge)',
      'Write and sign cashier documents (void report, cancel transaction, return report, expense report/petty cash)',
      'Standby Cashier',
      'Close sale report POS (End Day) and other assigned tasks',
      'Check customer complaints and team members\' job assignments',
      'Cleaning per monthly schedule (FS)',
      'Check promotion items, cashier promoting and stock availability at checkout counter',
      'End shift EOD and cash consolidation at back-end office',
      'Prepare and print Cashier document (Appendices 14)',
      'Standby at cashier checkout and support stock team for dry product preparation',
    ],
    weekly: [
      'Surprise cash count — Staff',
      'Update cash collection authorized list from treasury team',
      'Cash collection list report to SM office',
      'Training FS & IA to team member',
    ],
    monthly: [],
    quarterly: [],
  },
  {
    name: 'Mon Samun',
    role: 'Cashier',
    color: 'gray',
    daily: [
      'Receiving the cash float and count before SOD',
      'Clean checkout area and counter',
      'Checkout and customer service',
      'Break',
      'Checkout and customer service',
      'Prepare counter and clean',
      'Count money before EOD',
      'Support check expired Chinese goods near Checkout (Bakery goods)',
      'Support online order',
    ],
    weekly: [],
    monthly: [
      'Surprise Cashier',
    ],
    quarterly: [],
  },
  {
    name: 'Han Seakly',
    role: 'Cashier',
    color: 'gray',
    daily: [
      'Receiving the cash float and count before SOD',
      'Clean checkout area and counter',
      'Checkout and customer service',
      'Break',
      'Checkout and customer service',
      'Prepare counter and clean',
      'Count money before EOD',
      'Support check expired Chinese goods near Checkout (Bakery goods)',
      'Support online order',
    ],
    weekly: [],
    monthly: [
      'Surprise Cashier',
    ],
    quarterly: [],
  },
  {
    name: 'Sokha Thida',
    role: 'Chief Cashier',
    color: 'yellow',
    daily: [
      'Receiving the cash float and count before SOD',
      'Clean checkout area and counter',
      'Checkout and customer service',
      'Break',
      'Checkout and customer service',
      'Prepare counter and clean',
      'Count money before EOD',
      'Support check expired Chinese goods near Checkout (Bakery goods)',
      'Support online order',
    ],
    weekly: [],
    monthly: [
      'Surprise Cashier',
    ],
    quarterly: [],
  },
]

export const TEMPLATE_COLORS = {
  blue:   { bg: 'bg-blue-50',   text: 'text-blue-700',   border: 'border-blue-200',   dot: 'bg-blue-500'   },
  green:  { bg: 'bg-green-50',  text: 'text-green-700',  border: 'border-green-200',  dot: 'bg-green-500'  },
  yellow: { bg: 'bg-yellow-50', text: 'text-yellow-700', border: 'border-yellow-200', dot: 'bg-yellow-500' },
  orange: { bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200', dot: 'bg-orange-500' },
  purple: { bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200', dot: 'bg-purple-500' },
  red:    { bg: 'bg-red-50',    text: 'text-red-700',    border: 'border-red-200',    dot: 'bg-red-500'    },
  teal:   { bg: 'bg-teal-50',   text: 'text-teal-700',   border: 'border-teal-200',   dot: 'bg-teal-500'   },
  gray:   { bg: 'bg-gray-50',   text: 'text-gray-700',   border: 'border-gray-200',   dot: 'bg-gray-500'   },
  pink:   { bg: 'bg-pink-50',   text: 'text-pink-700',   border: 'border-pink-200',   dot: 'bg-pink-500'   },
}
